version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: kitchen-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kitchen_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kitchen-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    container_name: kitchen-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.1
    container_name: kitchen-schema-registry
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:9092"
    ports:
      - "8081:8081"
    depends_on:
      - kafka

volumes:
  mysql-data:
  kafka-data:
  zookeeper-data:
