/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hungerkiller.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class StockDepletedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5509937873884145681L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StockDepletedEvent\",\"namespace\":\"com.hungerkiller.events\",\"fields\":[{\"name\":\"itemId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"itemName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"restaurantId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"remainingQty\",\"type\":\"double\"},{\"name\":\"isOutOfStock\",\"type\":\"boolean\"},{\"name\":\"depleteAt\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StockDepletedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StockDepletedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StockDepletedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StockDepletedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StockDepletedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StockDepletedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StockDepletedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StockDepletedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StockDepletedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String itemId;
  private java.lang.String itemName;
  private java.lang.String restaurantId;
  private double remainingQty;
  private boolean isOutOfStock;
  private java.lang.String depleteAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StockDepletedEvent() {}

  /**
   * All-args constructor.
   * @param itemId The new value for itemId
   * @param itemName The new value for itemName
   * @param restaurantId The new value for restaurantId
   * @param remainingQty The new value for remainingQty
   * @param isOutOfStock The new value for isOutOfStock
   * @param depleteAt The new value for depleteAt
   */
  public StockDepletedEvent(java.lang.String itemId, java.lang.String itemName, java.lang.String restaurantId, java.lang.Double remainingQty, java.lang.Boolean isOutOfStock, java.lang.String depleteAt) {
    this.itemId = itemId;
    this.itemName = itemName;
    this.restaurantId = restaurantId;
    this.remainingQty = remainingQty;
    this.isOutOfStock = isOutOfStock;
    this.depleteAt = depleteAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return itemId;
    case 1: return itemName;
    case 2: return restaurantId;
    case 3: return remainingQty;
    case 4: return isOutOfStock;
    case 5: return depleteAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: itemId = value$ != null ? value$.toString() : null; break;
    case 1: itemName = value$ != null ? value$.toString() : null; break;
    case 2: restaurantId = value$ != null ? value$.toString() : null; break;
    case 3: remainingQty = (java.lang.Double)value$; break;
    case 4: isOutOfStock = (java.lang.Boolean)value$; break;
    case 5: depleteAt = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'itemId' field.
   * @return The value of the 'itemId' field.
   */
  public java.lang.String getItemId() {
    return itemId;
  }


  /**
   * Sets the value of the 'itemId' field.
   * @param value the value to set.
   */
  public void setItemId(java.lang.String value) {
    this.itemId = value;
  }

  /**
   * Gets the value of the 'itemName' field.
   * @return The value of the 'itemName' field.
   */
  public java.lang.String getItemName() {
    return itemName;
  }


  /**
   * Sets the value of the 'itemName' field.
   * @param value the value to set.
   */
  public void setItemName(java.lang.String value) {
    this.itemName = value;
  }

  /**
   * Gets the value of the 'restaurantId' field.
   * @return The value of the 'restaurantId' field.
   */
  public java.lang.String getRestaurantId() {
    return restaurantId;
  }


  /**
   * Sets the value of the 'restaurantId' field.
   * @param value the value to set.
   */
  public void setRestaurantId(java.lang.String value) {
    this.restaurantId = value;
  }

  /**
   * Gets the value of the 'remainingQty' field.
   * @return The value of the 'remainingQty' field.
   */
  public double getRemainingQty() {
    return remainingQty;
  }


  /**
   * Sets the value of the 'remainingQty' field.
   * @param value the value to set.
   */
  public void setRemainingQty(double value) {
    this.remainingQty = value;
  }

  /**
   * Gets the value of the 'isOutOfStock' field.
   * @return The value of the 'isOutOfStock' field.
   */
  public boolean getIsOutOfStock() {
    return isOutOfStock;
  }


  /**
   * Sets the value of the 'isOutOfStock' field.
   * @param value the value to set.
   */
  public void setIsOutOfStock(boolean value) {
    this.isOutOfStock = value;
  }

  /**
   * Gets the value of the 'depleteAt' field.
   * @return The value of the 'depleteAt' field.
   */
  public java.lang.String getDepleteAt() {
    return depleteAt;
  }


  /**
   * Sets the value of the 'depleteAt' field.
   * @param value the value to set.
   */
  public void setDepleteAt(java.lang.String value) {
    this.depleteAt = value;
  }

  /**
   * Creates a new StockDepletedEvent RecordBuilder.
   * @return A new StockDepletedEvent RecordBuilder
   */
  public static com.hungerkiller.events.StockDepletedEvent.Builder newBuilder() {
    return new com.hungerkiller.events.StockDepletedEvent.Builder();
  }

  /**
   * Creates a new StockDepletedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StockDepletedEvent RecordBuilder
   */
  public static com.hungerkiller.events.StockDepletedEvent.Builder newBuilder(com.hungerkiller.events.StockDepletedEvent.Builder other) {
    if (other == null) {
      return new com.hungerkiller.events.StockDepletedEvent.Builder();
    } else {
      return new com.hungerkiller.events.StockDepletedEvent.Builder(other);
    }
  }

  /**
   * Creates a new StockDepletedEvent RecordBuilder by copying an existing StockDepletedEvent instance.
   * @param other The existing instance to copy.
   * @return A new StockDepletedEvent RecordBuilder
   */
  public static com.hungerkiller.events.StockDepletedEvent.Builder newBuilder(com.hungerkiller.events.StockDepletedEvent other) {
    if (other == null) {
      return new com.hungerkiller.events.StockDepletedEvent.Builder();
    } else {
      return new com.hungerkiller.events.StockDepletedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for StockDepletedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StockDepletedEvent>
    implements org.apache.avro.data.RecordBuilder<StockDepletedEvent> {

    private java.lang.String itemId;
    private java.lang.String itemName;
    private java.lang.String restaurantId;
    private double remainingQty;
    private boolean isOutOfStock;
    private java.lang.String depleteAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.hungerkiller.events.StockDepletedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.itemId)) {
        this.itemId = data().deepCopy(fields()[0].schema(), other.itemId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.itemName)) {
        this.itemName = data().deepCopy(fields()[1].schema(), other.itemName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.restaurantId)) {
        this.restaurantId = data().deepCopy(fields()[2].schema(), other.restaurantId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.remainingQty)) {
        this.remainingQty = data().deepCopy(fields()[3].schema(), other.remainingQty);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.isOutOfStock)) {
        this.isOutOfStock = data().deepCopy(fields()[4].schema(), other.isOutOfStock);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.depleteAt)) {
        this.depleteAt = data().deepCopy(fields()[5].schema(), other.depleteAt);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing StockDepletedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.hungerkiller.events.StockDepletedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.itemId)) {
        this.itemId = data().deepCopy(fields()[0].schema(), other.itemId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.itemName)) {
        this.itemName = data().deepCopy(fields()[1].schema(), other.itemName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.restaurantId)) {
        this.restaurantId = data().deepCopy(fields()[2].schema(), other.restaurantId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.remainingQty)) {
        this.remainingQty = data().deepCopy(fields()[3].schema(), other.remainingQty);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.isOutOfStock)) {
        this.isOutOfStock = data().deepCopy(fields()[4].schema(), other.isOutOfStock);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.depleteAt)) {
        this.depleteAt = data().deepCopy(fields()[5].schema(), other.depleteAt);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'itemId' field.
      * @return The value.
      */
    public java.lang.String getItemId() {
      return itemId;
    }


    /**
      * Sets the value of the 'itemId' field.
      * @param value The value of 'itemId'.
      * @return This builder.
      */
    public com.hungerkiller.events.StockDepletedEvent.Builder setItemId(java.lang.String value) {
      validate(fields()[0], value);
      this.itemId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'itemId' field has been set.
      * @return True if the 'itemId' field has been set, false otherwise.
      */
    public boolean hasItemId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'itemId' field.
      * @return This builder.
      */
    public com.hungerkiller.events.StockDepletedEvent.Builder clearItemId() {
      itemId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'itemName' field.
      * @return The value.
      */
    public java.lang.String getItemName() {
      return itemName;
    }


    /**
      * Sets the value of the 'itemName' field.
      * @param value The value of 'itemName'.
      * @return This builder.
      */
    public com.hungerkiller.events.StockDepletedEvent.Builder setItemName(java.lang.String value) {
      validate(fields()[1], value);
      this.itemName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'itemName' field has been set.
      * @return True if the 'itemName' field has been set, false otherwise.
      */
    public boolean hasItemName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'itemName' field.
      * @return This builder.
      */
    public com.hungerkiller.events.StockDepletedEvent.Builder clearItemName() {
      itemName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'restaurantId' field.
      * @return The value.
      */
    public java.lang.String getRestaurantId() {
      return restaurantId;
    }


    /**
      * Sets the value of the 'restaurantId' field.
      * @param value The value of 'restaurantId'.
      * @return This builder.
      */
    public com.hungerkiller.events.StockDepletedEvent.Builder setRestaurantId(java.lang.String value) {
      validate(fields()[2], value);
      this.restaurantId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'restaurantId' field has been set.
      * @return True if the 'restaurantId' field has been set, false otherwise.
      */
    public boolean hasRestaurantId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'restaurantId' field.
      * @return This builder.
      */
    public com.hungerkiller.events.StockDepletedEvent.Builder clearRestaurantId() {
      restaurantId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'remainingQty' field.
      * @return The value.
      */
    public double getRemainingQty() {
      return remainingQty;
    }


    /**
      * Sets the value of the 'remainingQty' field.
      * @param value The value of 'remainingQty'.
      * @return This builder.
      */
    public com.hungerkiller.events.StockDepletedEvent.Builder setRemainingQty(double value) {
      validate(fields()[3], value);
      this.remainingQty = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'remainingQty' field has been set.
      * @return True if the 'remainingQty' field has been set, false otherwise.
      */
    public boolean hasRemainingQty() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'remainingQty' field.
      * @return This builder.
      */
    public com.hungerkiller.events.StockDepletedEvent.Builder clearRemainingQty() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'isOutOfStock' field.
      * @return The value.
      */
    public boolean getIsOutOfStock() {
      return isOutOfStock;
    }


    /**
      * Sets the value of the 'isOutOfStock' field.
      * @param value The value of 'isOutOfStock'.
      * @return This builder.
      */
    public com.hungerkiller.events.StockDepletedEvent.Builder setIsOutOfStock(boolean value) {
      validate(fields()[4], value);
      this.isOutOfStock = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'isOutOfStock' field has been set.
      * @return True if the 'isOutOfStock' field has been set, false otherwise.
      */
    public boolean hasIsOutOfStock() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'isOutOfStock' field.
      * @return This builder.
      */
    public com.hungerkiller.events.StockDepletedEvent.Builder clearIsOutOfStock() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'depleteAt' field.
      * @return The value.
      */
    public java.lang.String getDepleteAt() {
      return depleteAt;
    }


    /**
      * Sets the value of the 'depleteAt' field.
      * @param value The value of 'depleteAt'.
      * @return This builder.
      */
    public com.hungerkiller.events.StockDepletedEvent.Builder setDepleteAt(java.lang.String value) {
      validate(fields()[5], value);
      this.depleteAt = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'depleteAt' field has been set.
      * @return True if the 'depleteAt' field has been set, false otherwise.
      */
    public boolean hasDepleteAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'depleteAt' field.
      * @return This builder.
      */
    public com.hungerkiller.events.StockDepletedEvent.Builder clearDepleteAt() {
      depleteAt = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StockDepletedEvent build() {
      try {
        StockDepletedEvent record = new StockDepletedEvent();
        record.itemId = fieldSetFlags()[0] ? this.itemId : (java.lang.String) defaultValue(fields()[0]);
        record.itemName = fieldSetFlags()[1] ? this.itemName : (java.lang.String) defaultValue(fields()[1]);
        record.restaurantId = fieldSetFlags()[2] ? this.restaurantId : (java.lang.String) defaultValue(fields()[2]);
        record.remainingQty = fieldSetFlags()[3] ? this.remainingQty : (java.lang.Double) defaultValue(fields()[3]);
        record.isOutOfStock = fieldSetFlags()[4] ? this.isOutOfStock : (java.lang.Boolean) defaultValue(fields()[4]);
        record.depleteAt = fieldSetFlags()[5] ? this.depleteAt : (java.lang.String) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StockDepletedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<StockDepletedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StockDepletedEvent>
    READER$ = (org.apache.avro.io.DatumReader<StockDepletedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.itemId);

    out.writeString(this.itemName);

    out.writeString(this.restaurantId);

    out.writeDouble(this.remainingQty);

    out.writeBoolean(this.isOutOfStock);

    out.writeString(this.depleteAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.itemId = in.readString();

      this.itemName = in.readString();

      this.restaurantId = in.readString();

      this.remainingQty = in.readDouble();

      this.isOutOfStock = in.readBoolean();

      this.depleteAt = in.readString();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.itemId = in.readString();
          break;

        case 1:
          this.itemName = in.readString();
          break;

        case 2:
          this.restaurantId = in.readString();
          break;

        case 3:
          this.remainingQty = in.readDouble();
          break;

        case 4:
          this.isOutOfStock = in.readBoolean();
          break;

        case 5:
          this.depleteAt = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










